# Site settings
title: Blissful Breaks
top-nav: Benefit Cosmetics
description: >
  You needn’t go far this summer to catch that balmy glow – save a little on flights and spend the extra on a luxurious break that’s closer than you may think...
baseurl: "/blissful-breaks" # the subpath of your site, e.g. /blog/
url: "http://mp.secretescapes.com" # the base hostname & protocol for your site

# Build settings
markdown: kramdown
exclude: [node_modules, gulpfile.js, package.json, bower_components, bower.json, README.md]
